### ISSUE TITLE
NullPointerException in the plugin

### ISSUE THREAD

**Issue by viliam-durina** [avianey/androidsvgdrawable-plugin#37]
I get the following exception:

```
Caused by: java.lang.NullPointerException
    at fr.avianey.androidsvgdrawable.SvgDrawablePlugin.execute(SvgDrawablePlugin.java:146)
    at fr.avianey.androidsvgdrawable.gradle.SvgDrawableTask.svgToDrawable(SvgDrawableTask.java:67)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 47 more
```

I use the 1.0.2 version. Probably I did some configuration wrong (parameters seem to be null), but the error could be better.

**Comment by viliam-durina** [comment]
I found out I must copy the configuration parameters from the sample project.

If someone else falls into this problem, copy this: https://github.com/avianey/androidsvgdrawable-plugin/blob/master/sample/gradle/app/build.gradle, lines 33-56

**Comment by avianey** [comment]
I will add a pre process to verify required attribute from the build file...
